site_name: Oh My CAP
pages:
    - 引言: index.md
    - 写给初学者: intro.md
    - 安装: install.md
    - 快速开始: quick-start.md
    - 流程:
        - 流程介绍: procedures/intro-to-procedures.md
        - 计算格林函数: procedures/gflib.md
        - 数据预处理: procedures/preprocess.md
        - 反演: procedures/inversion.md
    - 反演参数: parameter.md
    - 版本发布: changelog.md
    - 代码差异: code-diffs.md
theme:
  name: 'material'
  favicon: 'img/favicon.ico'
  logo: 'img/favicon.ico'
  language: 'zh'
  palette:
    primary: 'blue'
    accent: 'indigo'
