site_name: Oh My CAP
site_url: https://wangliang.one/oh-my-cap/
site_author: wangliang1989
docs_dir: .
repo_url: https://github.com/wangliang1989/oh-my-cap

pages:
- 简介: index.md
- 安装: install.md
- 快速开始: quick-start.md
- 流程:
  - '流程简介': intro-to-procedures.md
  - '计算格林函数': gflib.md
  - '数据预处理': preprocess.md
  - '反演': inversion.md
- 反演参数: parameter.md
- 其他:
    - '代码差异': code-diffs.md
- FAQ: FAQs.md
